import './globals.css'
import { Inter } from 'next/font/google'
import { Poppins } from 'next/font/google'
import { Bungee_Outline } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['600', '500', '300'],
  variable: '--font-poppins'
})

const bungee = Bungee_Outline({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-bungee'
})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${bungee.variable}`}>{children}</body>
    </html>
  )
}
